name: Nifty Opening Predictor
on:
  schedule:
    - cron: '35 3 * * *' # Runs at 03:35 UTC (05:35 AM Tete)
  workflow_dispatch:      # Allows you to run it manually anytime
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script.py
        
